# Generated by Django 5.2.12 on 2026-07-02 02:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Application name (e.g., Campus Eats, Reconna)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique API code to identify the app (e.g., campuseats, reconna)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the application')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this app is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'apps',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the access tier (e.g., Basic, Premium, Enterprise)', max_length=100)),
                ('key_prefix', models.CharField(help_text='Prefix for generated subscription keys (e.g., basic_, prem_, ent_)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of what this tier offers')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Number of days a subscription to this tier is valid')),
                ('max_requests_per_day', models.PositiveIntegerField(default=100, help_text='Maximum API requests allowed per day')),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=1, help_text='Maximum concurrent sessions allowed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tier is currently available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(blank=True, help_text='The application this tier belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to='subscriptions.app')),
            ],
            options={
                'verbose_name': 'Access Key Tier',
                'verbose_name_plural': 'Access Key Tiers',
                'db_table': 'access_keys',
                'ordering': ['app__name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Email of the subscriber', max_length=254)),
                ('user_name', models.CharField(help_text='Name of the subscriber', max_length=100)),
                ('generated_key', models.CharField(editable=False, help_text='The generated API key for this subscription', max_length=64, unique=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the subscription starts')),
                ('end_date', models.DateTimeField(help_text='When the subscription expires')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_key', models.ForeignKey(help_text='The access tier this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.accesskey')),
                ('app', models.ForeignKey(blank=True, help_text='The application this subscription belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.app')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
