# Generated by Django 4.1 on 2025-08-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterModelOptions(
            name='countrylink',
            options={'ordering': ['country_name'], 'verbose_name_plural': 'Country Links'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='countrylink',
            table='country_links',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='eventsubscription',
            table='event_subscriptions',
        ),
    ]
