# Generated by Django 5.2.12 on 2026-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_apikey_article_dislikes_article_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user_agent', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('page_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'active_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_active', models.BooleanField(default=True, help_text='Toggle to activate/deactivate the entire site')),
                ('maintenance_message', models.TextField(default='Site is currently under maintenance. Please check back later.', help_text='Message to show when site is deactivated')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
